name: single_child_two_dimensional_scroll_view
description: "A box in which a single widget can be scrolled in two dimensions"
version: 0.1.0
homepage: https://github.com/sjhorn/single_child_two_dimensional_scroll_view/tree/main

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
